config/routes.rb
Sentinelle::Application.routes.draw do
  resources :plans

  resources :occorrences do
    get :autocomplete_user_name, :on => :collection
    member do
      get "execution"
      put "close"
    end
  end

  resources :assets do
    get :autocomplete_asset_name, :on => :collection
  end

  resources :providers

  resources :groups do
    member do
      get 'subgroups_by_group'
    end
  end
  
  resources :messages, :only => [:index, :show]

  resources :locals

  root "home#index"
  resources :home, :only => [:index] 

  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :occorrence
  validates_presence_of :user_id
  validates_presence_of :subject
  validates_presence_of :body
  def self.send_message(user_id, subject, body, occorrence_id)
    message = Message.new
    message.user_id = user_id
    message.subject = subject
    message.body = body
    message.occorrence_id = occorrence_id
    message.save
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.where("user_id = ?", current_user.id)
  end
  
  def show
    @message = Message.find(params[:id])
    @message.read = true
    @message.save
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Mensagens
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>         
	      <div class="box-container-toggle">
	          <div class="box-content">
							<h2>Mensagens</h2>
	            
             <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered bootstrap-datatable dataTable" aria-describedby="datatable_info">
	             <thead>
                      <tr>
                          <th>Data</th>
                          <th>Assunto</th>
                          <th>Ocorrência</th>                                     
                      </tr>
                  </thead>   
                  <tbody>
                    <% @messages.each do |msg| %>
				      <tr>
				        <td> <%= msg.created_at.strftime("%d/%m/%Y %H:%M") %></td>
				        <td> 
									<% if msg.read %>
									  <%= link_to message_path(msg.id) do %> <%= msg.subject %> <% end %>
									<% else %>
									  <b><%= link_to message_path(msg.id) do %> <%= msg.subject %> <% end %></b>
									<% end %>
								</td>
				        <td> <%= link_to "##{msg.occorrence_id}", edit_occorrence_path(msg.occorrence_id) %></td>
				      </tr>
				    <% end %>
                  </tbody>
             </table>
							 
	          </div>
	      </div>
	    </div><!--/span-->
	 </div>
</div>

<script>
  applyDataTable();
</script>

app/views/messages/show.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Mensagem - <%= @message.created_at.strftime("%d/%m/%Y %H:%M")%>
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>
	     	<div class="box-container-toggle">
               <div class="box-content">
								 <div class="form-vertical">
						 		  <div class="control-group">
						 			<label class="control-label" for="focusedInput">Assunto</label>
						 		    <div class="controls">
						 		      <%= text_field_tag :subject, @message.subject, :readonly => true, :class => "span12"%>
						 		    </div>
						 		  </div>
								  <div class="control-group">
									<label class="control-label" for="focusedInput">Texto</label>
								    <div class="controls">
								      <%= text_area_tag :body, @message.body.html_safe, :readonly => true, :rows => 10, :class => "span12"%>
								    </div>
								  </div>
							    <hr>
							    <%= link_to 'Voltar', messages_path, :class => "btn" %> | 
									<%= link_to 'Ocorrência', edit_occorrence_path(@message.occorrence_id), :class => "btn"%>
								 </div>
	           </div>
	        </div>
	      </div>
    </div>
</div>