config/routes.rb
Sentinelle::Application.routes.draw do
  resources :plans

  resources :occorrences do
    get :autocomplete_user_name, :on => :collection
    member do
      get "execution"
      put "close"
    end
  end

  resources :assets do
    get :autocomplete_asset_name, :on => :collection
  end

  resources :providers

  resources :groups do
    member do
      get 'subgroups_by_group'
    end
  end
  
  resources :messages, :only => [:index, :show]

  resources :locals

  root "home#index"
  resources :home, :only => [:index] 

  

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :group_id
  validates_presence_of :subgroup_id
  validates_presence_of :enterprise_id
  belongs_to :provider_warranty, :class_name => "Provider", :foreign_key => "provider_warranty_id"
  belongs_to :provider_technical_assistance, :class_name => "Provider", :foreign_key => "provider_technical_assistance_id"
  belongs_to :group
  belongs_to :subgroup
  belongs_to :local
  belongs_to :enterprise
  has_many :asset_specifications, :class_name => "AssetSpecification", :foreign_key => "asset_id"
  accepts_nested_attributes_for :asset_specifications, reject_if: :all_blank, allow_destroy: true
  scope :search_by_name_or_number, ->(name) { where("name ilike '%?%' or number_of_equity = '?'", name, name) }
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]
  autocomplete :asset, :name, :full => true, :scope => [:search_by_name_or_number]
  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.where("enterprise_id = ?", current_user.enterprise_id)
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
    init_collections
  end

  # GET /assets/1/edit
  def edit
    init_collections
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to assets_path, notice: 'Asset was successfully created.' }
        format.json { render action: 'show', status: :created, location: @asset }
      else 
        init_collections
        format.html { render action: 'new' }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to assets_path, notice: 'Asset was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end
    
    def init_collections
      @groups = Group.where("enterprise_id = ?", current_user.enterprise_id)
      @locals = Local.where("enterprise_id = ?", current_user.enterprise_id)
      @providers = Provider.where("enterprise_id = ? and kind = 2", current_user.enterprise_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:enterprise_id, :group_id, :subgroup_id, :number_of_equity, :name, :description, :acquisition_date, :provider_warranty_id, :provider_technical_assistance_id, :warranty_date, :local_id, :technical_specifications)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= nested_form_for @asset, :class => "form-horizontal" do |f| %>
  <%= render :partial => "shared/error_messages", :locals => {:target => @asset} %>
  <fieldset>
      <legend>Ativo</legend>
      <div class="row-fluid">
	    <div class="span2">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Tombamento</label>
		    <div class="controls">
		      <%= f.text_field :number_of_equity, :class => "span12"%>
		    </div>
		  </div>
		</div>
	    <div class="span8">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Nome*</label>
		    <div class="controls">
		      <%= f.text_field :name, :class => "span12"%>
		    </div>
		  </div>
		</div>		
		<div class="span2">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Data de aquisição</label>
		    <div class="controls">
		      <%= f.text_field :acquisition_date, :class => "span12 datepicker"%>
		    </div>
		  </div>
		</div>
	  </div>
	  <div class="row-fluid">
		<div class="span4">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Grupo*</label>
		    <div class="controls">
		      <%= f.collection_select :group_id, @groups, :id, :name, {include_blank: true}, {:class => "span12", :onchange => "load_subgroups()"}%>
		    </div>
		  </div>
		</div>
		<div class="span4">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Subgrupo*</label>
		    <div class="controls">
		      <%= f.collection_select :subgroup_id, [], :id, :name, {include_blank: true}, {:class => "span12"}%>
		    </div>
		  </div>
		</div>
		<div class="span4">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Local</label>
		    <div class="controls">
		      <%= f.collection_select :local_id, @locals, :id, :name, {include_blank: true}, {:class => "span12"}%>
		    </div>
		  </div>
		</div>
	  </div>
	  <div class="row-fluid">
		<div class="span12">
		  <div class="control-group">
		    <label class="control-label" for="focusedInput">Descrição</label>
			<div class="controls">
			  <%= f.text_area :description, :class => "span12"%>
			</div>
		  </div>
		</div>
	  </div>
      
      <%= f.hidden_field :enterprise_id, :value => current_user.enterprise_id%>
      <h4>Assitência técnica e garantia</h4>
      <hr>
      <div class="row-fluid">
	    <div class="span5">
		  <div class="control-group">
		    <label class="control-label" for="focusedInput">Ass. técnica</label>
			<div class="controls">
			  <%= f.collection_select :provider_technical_assistance_id, @providers, :id, :name, {include_blank: true}, {:class => "span12"}%>
			</div>
		  </div>
		</div>
		<div class="span5">
		  <div class="control-group">
		    <label class="control-label" for="focusedInput">Garantia</label>
			<div class="controls">
			  <%= f.collection_select :provider_warranty_id, @providers, :id, :name, {include_blank: true}, {:class => "span12"}%>
			</div>
		  </div>
		</div>
		<div class="span2">
		  <div class="control-group">
			<label class="control-label" for="focusedInput">Data da garantia</label>
		    <div class="controls">
		      <%= f.text_field :acquisition_date, :class => "span12 datepicker"%>
		    </div>
		  </div>
		</div>
	  </div>
	  <h4>Especificações técnicas</h4>
      <hr>
      <div class="row-fluid">
		<div class="span12">
		  <div class="control-group">
		    <label class="control-label" for="focusedInput">Descrição</label>
			<div class="controls">
			  <%= f.text_area :technical_specifications, :class => "span12", :rows => 5%>
			</div>
		  </div>
		</div>
	  </div>
    </fieldset>
    <hr>
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large"%> | 
    <%= link_to 'Cancelar', groups_path, :class => "btn btn-danger" %>
  
<% end %>


<script>
  function load_subgroups(){
  	var group_id = $("#asset_group_id").val();
  	$.ajax({
  		type: "GET",
  		dataType: "json",
  		url: "/groups/" + group_id + "/subgroups_by_group"
  	}).done(function( json ) {
  		var options = "";
        $.each(json, function(key, value){
        	options += '<option value="' + value.id + '">' +  value.name + '</option>';
        });
        $("#asset_subgroup_id").html(options);
  	});
  };

  <% unless @asset.new_record? %>
    load_subgroups();
  <% end %>
  applyDatePicker();
</script>

app/views/assets/edit.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Cadastro de ativos - Edição
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>
	     	<div class="box-container-toggle">
               <div class="box-content">
	              <%= render 'form' %>
	           </div>
	        </div>
	      </div>
    </div>
</div>

app/views/assets/index.html.erb
<div class="row-fluid">
        <div class="span2 action-btn round-all">
        	<%= link_to new_asset_path do %>
                <div><i class="icon-pencil"></i></div>
                <div><strong>Novo</strong></div>        	
            <% end %>
        </div>
        
</div>
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Lista de ativos
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>         
	      <div class="box-container-toggle">
	          <div class="box-content">
				 <h2>Ativos</h2>
	             <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered bootstrap-datatable dataTable" aria-describedby="datatable_info">
		             <thead>
	                      <tr>
	                          <th>#</th>
	                          <th>Tombamento</th>
	                          <th>Descrição</th>
	                          <th>Ações</th>                                          
	                      </tr>
	                  </thead>   
	                  <tbody>
	                    <% @assets.each do |asset| %>
					      <tr>
					        <td class="center"><%= asset.id %></td>
					        <td> <%= asset.number_of_equity %></td>
					        <td> <%= asset.name %></td>
					        <td>
					          <%= link_to edit_asset_path(asset), :class => "btn btn-success" do %>
					            <i class="icon-edit icon-white"></i> Editar
					          <% end %> 
					          <%= link_to asset, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
					            <i class="icon-trash icon-white"></i> Excluir
					          <% end %>
					        </td>
					      </tr>
					    <% end %>
	                  </tbody>
	             </table>
	          </div>
	      </div>
	    </div><!--/span-->
	 </div>
</div>
<script>
  applyDataTable();
</script>

app/views/assets/new.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Cadastro de ativos - Novo
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>
	     	<div class="box-container-toggle">
               <div class="box-content">
	              <%= render 'form' %>
	           </div>
	        </div>
	      </div>
    </div>
</div>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>