config/routes.rb
Sentinelle::Application.routes.draw do
  resources :plans

  resources :occorrences do
    get :autocomplete_user_name, :on => :collection
    member do
      get "execution"
      put "close"
    end
  end

  resources :assets do
    get :autocomplete_asset_name, :on => :collection
  end

  resources :providers

  resources :groups do
    member do
      get 'subgroups_by_group'
    end
  end
  
  resources :messages, :only => [:index, :show]

  resources :locals

  root "home#index"
  resources :home, :only => [:index] 

  

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :enterprise_id
  belongs_to :enterprise
  has_many :plan_activities, :class_name => "PlanActivity", :foreign_key => "plan_id"
  has_many :plan_applications, :class_name => "PlanApplication", :foreign_key => "plan_id"
  accepts_nested_attributes_for :plan_activities, :allow_destroy => true#, reject_if: :all_blank
  accepts_nested_attributes_for :plan_applications, :allow_destroy => true#, reject_if: :all_blank
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.where("enterprise_id = ?", current_user.enterprise_id)
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    init_collections
  end

  # GET /plans/1/edit
  def edit
    init_collections
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plans_path, notice: 'Plan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @plan }
      else
        init_collections
        format.html { render action: 'new' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plans_path, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        init_collections
        format.html { render action: 'edit' }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end

  private
    def init_collections
      @groups = Group.where("enterprise_id = ?", current_user.enterprise_id)
      @subgroups = Subgroup.joins(:group).where("enterprise_id = ?", current_user.enterprise_id).select("subgroups.id, subgroups.name || ' [' || groups.name || ']' as name ")
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:enterprise_id, :name, :plan_activities_attributes => [:id, :plan_id, :name, :kind, :unity, :value], :plan_applications_attributes => [:id, :group_id, :subgroup_id, :asset_id])
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= nested_form_for @plan, :class => "form-horizontal" do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	<fieldset>
      <legend>Plano de manutenção</legend>
			<%= f.hidden_field :enterprise_id, :value => current_user.enterprise_id%>
      <div class="control-group">
        <label class="control-label" for="focusedInput">Nome</label>
        <div class="controls">
          <%= f.text_field :name%>
        </div>
      </div>
			<h4>Atividades</h4>
			<%= f.fields_for :plan_activities do |activity| %>
			<div class="row-fluid">
				<div class="span5">
			    <div class="control-group">
			        <label class="control-label" for="focusedInput">Descrição*</label>
			        <div class="controls">
			          <%= activity.text_field :name, :class => "span12" %>
			        </div>
			    </div>
				</div>
				<div class="span2">
			    <div class="control-group">
			        <label class="control-label" for="focusedInput">Tipo*</label>
			        <div class="controls">
			          <%= activity.select :kind, options_for_select(PlanActivity::KIND_LIST, activity.object.kind), { include_blank: true }, {:class => "span12"} %>
			        </div>
			    </div>
				</div>
				<div class="span2">
			    <div class="control-group">
			        <label class="control-label" for="focusedInput">Unidade*</label>
			        <div class="controls">
			          <%= activity.select :unity, options_for_select(PlanActivity::UNITY_LIST, activity.object.unity), { include_blank: true }, {:class => "span12"} %>
			        </div>
			    </div>
				</div>
				<div class="span2">
			    <div class="control-group">
			        <label class="control-label" for="focusedInput">Valor*</label>
			        <div class="controls">
			          <%= activity.text_field :value, :class => "span12" %>
			        </div>
			    </div>
				</div>
				<div class="span1">
					<div class="control-group">
				        <label class="control-label" for="focusedInput">Remover</label>
				        <div class="controls">
			              <%= activity.link_to_remove "X", :class => "btn btn-danger" %>	          
				        </div>
				    </div>
				</div>
			</div>
			<% end %>
			<p><%= f.link_to_add "Nova atividade", :plan_activities, :class => "btn" %></p>
			<hr>
			<h4>Aplicar em</h4>
			<%= f.fields_for :plan_applications do |app| %>
			<div class="row-fluid">
				<div class="span3">
					<div class="control-group">
						<label class="control-label" for="focusedInput">Grupo</label>
						<div class="controls">
							<%= app.collection_select :group_id, @groups, :id, :name, {include_blank: true}, {:class => "span12 group"}%>
						</div>
					</div>
				</div>
				<div class="span4">
					<div class="control-group">
						<label class="control-label" for="focusedInput">Subgrupo</label>
						<div class="controls">
							<%= app.collection_select :subgroup_id, @subgroups, :id, :name, {include_blank: true}, {:class => "span12"}%>
						</div>
					</div>
				</div>
		    <div class="span4">
			    <div class="control-group">
						<label class="control-label" for="focusedInput">Ativo</label>
			      <div class="controls">
							<%= app.autocomplete_field :asset_name, autocomplete_asset_name_assets_path, :class => "span12", :update_elements => {:id => form_tag_id(app.object_name, :asset_id)}%>
							<%= app.hidden_field :asset_id%>
			      </div>
			    </div>
			  </div>
				<div class="span1">
					<div class="control-group">
				        <label class="control-label" for="focusedInput">Remover</label>
				        <div class="controls">
			              <%= app.link_to_remove "X", :class => "btn btn-danger" %>	          
				        </div>
				    </div>
				</div>
			</div>
			<% end %>
			<p><%= f.link_to_add "Nova aplicação", :plan_applications, :class => "btn" %></p>
			<hr>
    </fieldset>
    <hr>
    <%= f.submit "Salvar", :class => "btn btn-primary btn-large"%> | 
    <%= link_to 'Cancelar', plans_path, :class => "btn btn-danger" %>
  
<% end %>

app/views/plans/edit.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Editar plano
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>
	     	<div class="box-container-toggle">
               <div class="box-content">
	              <%= render 'form' %>
	           </div>
	        </div>
	      </div>
    </div>
</div>

app/views/plans/index.html.erb
<div class="row-fluid">
        <div class="span2 action-btn round-all">
        	<%= link_to new_plan_path do %>
                <div><i class="icon-pencil"></i></div>
                <div><strong>Novo</strong></div>        	
            <% end %>
        </div>
        
</div>
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Lista de planos de manutenção
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>         
	      <div class="box-container-toggle">
	          <div class="box-content">
				 <h2>Planos de manutenção</h2>
	             <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered bootstrap-datatable dataTable" aria-describedby="datatable_info">
		             <thead>
	                      <tr>
	                          <th>#</th>
	                          <th>Nome</th>
	                          <th>Ações</th>                                          
	                      </tr>
	                  </thead>   
	                  <tbody>
	                    <% @plans.each do |plan| %>
					      <tr>
					        <td class="center"><%= plan.id %></td>
					        <td> <%= plan.name %></td>
					        <td>
					          <%= link_to edit_plan_path(plan), :class => "btn btn-success" do %>
					            <i class="icon-edit icon-white"></i> Editar
					          <% end %>
					          <%= link_to plan, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } do %>
					            <i class="icon-trash icon-white"></i> Cancelar
					          <% end %>
					        </td>
					      </tr>
					    <% end %>
	                  </tbody>
	             </table>
	          </div>
	      </div>
	    </div><!--/span-->
	 </div>
</div>

<script>
  applyDataTable();
</script>

app/views/plans/new.html.erb
<div class="row-fluid"> 
	<div class="span12">
	 	 <!-- Portlet: Fancy Portlets -->
	     <div class="box">
	      <h4 class="box-header round-top">Novo plano
	          <a class="box-btn" title="close"><i class="icon-remove"></i></a>
	          <a class="box-btn" title="toggle"><i class="icon-minus"></i></a>     
	          <a class="box-btn" title="config" data-toggle="modal" href="#box-config-modal"><i class="icon-cog"></i></a>
	      </h4>
	     	<div class="box-container-toggle">
               <div class="box-content">
	              <%= render 'form' %>
	           </div>
	        </div>
	      </div>
    </div>
</div>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>