config/routes.rb
Sentinelle::Application.routes.draw do
  resources :plans

  resources :occorrences do
    get :autocomplete_user_name, :on => :collection
    member do
      get "execution"
      put "close"
    end
  end

  resources :assets do
    get :autocomplete_asset_name, :on => :collection
  end

  resources :providers

  resources :groups do
    member do
      get 'subgroups_by_group'
    end
  end
  
  resources :messages, :only => [:index, :show]

  resources :locals

  root "home#index"
  resources :home, :only => [:index] 

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Sentinelle</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="HTML5 Admin Simplenso Template">
  <meta name="author" content="ahoekie">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- Bootstrap Image Gallery styles -->
  <link rel="stylesheet" href="http://blueimp.github.com/Bootstrap-Image-Gallery/css/bootstrap-image-gallery.min.css">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body id="dashboard">
     <!-- Top navigation bar -->
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container-fluid">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="index.html">Sentinelle</a>
	      <div class="btn-group pull-right">
	        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	          <i class="icon-user"></i> <John Doe > <%= current_user.name %>
	          <span class="caret"></span>
	        </a>
	        <ul class="dropdown-menu">
	          <li><a href="#">Profile</a></li>
	          <li><a href="#">Settings</a></li>
	          <li><a class="cookie-delete" href="#">Delete Cookies</a></li>
	          <li class="divider"></li>
	          <li><%= link_to "Sair", sign_out_path, :method => :delete %></li>
	        </ul>
	      </div>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li class="dropdown">
							<%= link_to messages_path, :class => "dropdown-toggle",
	                    :data_toggle => "dropdown" do %>
											Mensagens <span class="badge badge-info">100</span>
							<% end %>
	              <ul class="dropdown-menu">
	                  <li><a href="#">Message 1</a></li>
	                  <li><a href="#">Another message</a></li>
	                  <li><a href="#">Something else message</a></li>
	                  <li class="divider"></li>
	                  <li><a href="#">Older messages...</a></li>
	              </ul>
	          </li>	         
	        </ul>
	      </div><!--/.nav-collapse -->
	    </div>
	  </div>
	</div>
	<!-- Main Content Area | Side Nav | Content -->    
	<div class="container-fluid">
	  <div class="row-fluid">
	    <!-- Side Navigation -->
	    <div class="span2">
	      <div class="member-box round-all"> 
	        <a><img src="images/member_ph.png" class="member-box-avatar" /></a>
	        <span>
	            <strong>Usuário:</strong><br/>
	            <a><%= current_user.name %></a><br/>
	            <span class="member-box-links"><a>Settings</a> | <%= link_to "Sair", sign_out_path, :method => :delete %></span>
	        </span>
	      </div>          
	      <div class="sidebar-nav">
	      	<div class="well" style="padding: 8px 0;">
	        <ul class="nav nav-list"> 
	          <li class="nav-header">Principal</li>        
	          <li class="active"><a href="index.html"><i class="icon-home"></i> Início</a></li>
	          <li><%= link_to assets_path do %><i class="icon-edit"></i> Ativos<% end %></li>
	          <li><%= link_to occorrences_path do %><i class="icon-wrench"></i> Ocorrências<% end %></li>
	          <li class="nav-header">Manutenção</li>
	          <li><%= link_to plans_path do %><i class="icon-th"></i> Planos<% end %></li>
	          <li><a href="forms.html"><i class="icon-th"></i> Leituras</a></li>
	          <li class="nav-header">Cadastros</li>	
	          <li><%= link_to providers_path do %><i class="icon-align-justify"></i> Prestadores<% end %></li>
	          <li><%= link_to locals_path do %><i class="icon-align-justify"></i> Locais<% end %></li>
	          <li><%= link_to groups_path do %><i class="icon-align-justify"></i> Grupos/Subgrupos<% end %></li>
	          <li><a href="tables.html"><i class="icon-align-justify"></i> Usuários</a></li>
	        </ul>
	        </div>
	      </div><!--/.well -->
	    </div><!--/span-->

	    <!-- Bread Crumb Navigation -->
		<div class="span10">
	      <div>
	        <ul class="breadcrumb">
	          <li>
	            <a href="#">Home</a> <span class="divider">/</span>
	          </li>
	          <li>
	            <a href="#">Library</a> <span class="divider">/</span>
	          </li>
	          <li class="active">Data</li>
	        </ul>
	      </div>

	      <!-- Geographic Page Visit Map -->
	      <% if flash[:notice] %>
	        <div class="row-fluid"> 
				<div class="span12">
					<div class="alert alert-success"><%= flash[:notice] %></div>
				</div>
			</div>
		  
		  <% end %>
	      <%= yield %>

	    </div><!--/span-->
	  </div><!--/row-->

	  <footer>
	    <p>&copy; Simplenso 2012</p>
	  </footer>
	    <div id="box-config-modal" class="modal hide fade in" style="display: none;">
	      <div class="modal-header">
	        <button class="close" data-dismiss="modal">×</button>
	        <h3>Adjust widget</h3>
	      </div>
	      <div class="modal-body">
	        <p>This part can be customized to set box content specifix settings!</p>
	      </div>
	      <div class="modal-footer">
	        <a href="#" class="btn btn-primary" data-dismiss="modal">Save Changes</a>
	        <a href="#" class="btn" data-dismiss="modal">Cancel</a>
	      </div>
	    </div>
	</div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sentinelle</title>
<%= stylesheet_link_tag "login" %> 

</head>

<body id="background_gradient">
	<%= yield %>
</body>
</html>